/* ============================================================================
   IRON INVEST — реестр документов по объекту. Стадийная модель.

   Источник: greece-object-documents-checklist.md (ПЛ, 26.08.2026).
   Файл сгенерирован из него, правки вносить в источник и перегенерировать.

   Принцип: объект не переходит на следующую стадию, пока не закрыты все
   блокирующие документы предыдущей. Это заменяет доверие к посредникам
   проверяемым признаком.

   ── ЧТО СЮДА НЕ ПОПАЛО ────────────────────────────────────────────────────
   В источнике есть строки, объясняющие требования через конкретных людей.
   Портал публичный: требование переносится, объяснение через человека — нет.
   ============================================================================ */
(function () {
  window.IronDocs = {
    /* стадии: n, название, цель, задан ли признак блокировки */
    stages: [
      { n: 0, title: 'Скрининг (до задатка, до любых денег)', goal: 'за 3-5 дней понять, стоит ли объект расходов на полноценный due diligence.', hasBlockFlag: true },
      { n: 1, title: 'Юридический due diligence (до подписания предварительного)', goal: 'подтвердить, что продавец действительно собственник, объект чист и на нем можно строить то, что мы планируем.', hasBlockFlag: true },
      { n: 2, title: 'Сделка покупки', goal: null, hasBlockFlag: true },
      { n: 3, title: 'Проектирование и разрешения (до начала работ)', goal: null, hasBlockFlag: true },
      { n: 4, title: 'Подрядчики и договорная база', goal: null, hasBlockFlag: true },
      { n: 5, title: 'Строительство (текущее ведение)', goal: null, hasBlockFlag: false },
      { n: 6, title: 'Завершение и ввод', goal: null, hasBlockFlag: true },
      { n: 7, title: 'Пакет к продаже (маркетинг)', goal: null, hasBlockFlag: false },
      { n: 8, title: 'Юридический пакет продавца (что должно быть на руках до первого показа)', goal: null, hasBlockFlag: false },
      { n: 9, title: 'Сделка продажи покупателю', goal: null, hasBlockFlag: false },
      { n: 10, title: 'Пакет Golden Visa (если объект продается под ВНЖ)', goal: null, hasBlockFlag: false },
      { n: 11, title: 'Эксплуатация и аренда (если объект остается в портфеле)', goal: null, hasBlockFlag: false },
      { n: 'S', title: 'Сквозные документы', goal: null, hasBlockFlag: false },
    ],

    /* статусы документа — единственный допустимый словарь */
    statuses: ['none', 'requested', 'received', 'verified', 'expiring', 'expired', 'na'],

    /* типы объектов: набор документов зависит от типа */
    types: ['plot', 'house', 'houseUnfinished', 'commercialConversion', 'apartment', 'shop', 'hotel'],

    /* 177 позиций. status/dates заполняются по факту, здесь их нет. */
    items: [
      { id: '0.1', stage: 0, group: null, ru: 'Копия титула текущего собственника', gr: 'Τίτλος ιδιοκτησίας (συμβόλαιο)', issuer: 'Продавец', blocking: 'yes', cond: null, period: null },
      { id: '0.2', stage: 0, group: null, ru: 'Выписка из Кадастра, номер КАЕК', gr: 'Απόσπασμα κτηματολογικού φύλλου / ΚΑΕΚ', issuer: 'Κτηματολόγιο', blocking: 'yes', cond: null, period: null },
      { id: '0.3', stage: 0, group: null, ru: 'Кадастровая схема участка', gr: 'Απόσπασμα κτηματολογικού διαγράμματος', issuer: 'Κτηματολόγιο', blocking: 'yes', cond: null, period: null },
      { id: '0.4', stage: 0, group: null, ru: 'Топосъемка (если есть у продавца)', gr: 'Τοπογραφικό διάγραμμα', issuer: 'Инженер продавца', blocking: 'no', cond: null, period: null },
      { id: '0.5', stage: 0, group: null, ru: 'Фото и видеофиксация объекта на дату осмотра', gr: '-', issuer: 'Наша команда', blocking: 'yes', cond: null, period: null },
      { id: '0.6', stage: 0, group: null, ru: 'Акт первичного осмотра с координатами GPS', gr: '-', issuer: 'Наша команда', blocking: 'yes', cond: null, period: null },
      { id: '0.7', stage: 0, group: null, ru: 'Скрининг-справка: цена, площадь, зона, ограничения', gr: '-', issuer: 'Наша команда', blocking: 'yes', cond: null, period: null },
      { id: '0.8', stage: 0, group: null, ru: 'Предварительный расчет экономики (вход, capex, выход)', gr: '-', issuer: 'Наша команда', blocking: 'yes', cond: null, period: null },
      { id: '0.9', stage: 0, group: null, ru: 'Решение по объекту: идем / не идем / условно', gr: '-', issuer: 'ПЛ', blocking: 'yes', cond: null, period: null },
      { id: '1.1', stage: 1, group: 'Титул и обременения', ru: 'Цепочка титулов минимум за 20 лет', gr: 'Ιστορικό τίτλων 20ετίας', issuer: 'Адвокат / Υποθηκοφυλακείο', blocking: 'yes', cond: null, period: null },
      { id: '1.2', stage: 1, group: 'Титул и обременения', ru: 'Справка об обременениях', gr: 'Πιστοποιητικό βαρών', issuer: 'Υποθηκοφυλακείο / Κτηματολόγιο', blocking: 'yes', cond: null, period: null },
      { id: '1.3', stage: 1, group: 'Титул и обременения', ru: 'Справка об отсутствии претензий третьих лиц', gr: 'Πιστοποιητικό μη διεκδικήσεων', issuer: 'Υποθηκοφυλακείο', blocking: 'yes', cond: null, period: null },
      { id: '1.4', stage: 1, group: 'Титул и обременения', ru: 'Справка об отсутствии арестов', gr: 'Πιστοποιητικό μη κατασχέσεων', issuer: 'Υποθηκοφυλακείο', blocking: 'yes', cond: null, period: null },
      { id: '1.5', stage: 1, group: 'Титул и обременения', ru: 'Справка о регистрации права', gr: 'Πιστοποιητικό μεταγραφής / ιδιοκτησίας', issuer: 'Κτηματολόγιο', blocking: 'yes', cond: null, period: null },
      { id: '1.6', stage: 1, group: 'Титул и обременения', ru: 'Свидетельство о наследстве, если титул наследственный', gr: 'Πιστοποιητικό κληρονομιάς, αποδοχή κληρονομιάς', issuer: 'Нотариус', blocking: 'yes', cond: null, period: null },
      { id: '1.7', stage: 1, group: 'Титул и обременения', ru: 'Согласия сособственников и супругов', gr: '-', issuer: 'Продавец', blocking: 'yes', cond: null, period: null },
      { id: '1.8', stage: 1, group: 'Титул и обременения', ru: 'Юридическое заключение адвоката по титулу', gr: 'Νομικός έλεγχος', issuer: 'Наш адвокат (не продавца)', blocking: 'yes', cond: null, period: null },
      { id: '1.9', stage: 1, group: 'Правовой режим земли и застройки', ru: 'Топосъемка с координатами ЕГСА87 и декларациями', gr: 'Τοπογραφικό διάγραμμα (ΕΓΣΑ87, Ν.651/1977, Ν.4178/2013)', issuer: 'Наш инженер', blocking: 'yes', cond: null, period: null },
      { id: '1.10', stage: 1, group: 'Правовой режим земли и застройки', ru: 'Справка о пригодности и застраиваемости участка', gr: 'Βεβαίωση αρτιότητας και οικοδομησιμότητας', issuer: 'Υπηρεσία Δόμησης (ΥΔΟΜ)', blocking: 'yes', cond: null, period: null },
      { id: '1.11', stage: 1, group: 'Правовой режим земли и застройки', ru: 'Справка о показателях застройки: коэффициенты, этажность, отступы', gr: 'Όροι δόμησης', issuer: 'ΥΔΟΜ', blocking: 'yes', cond: null, period: null },
      { id: '1.12', stage: 1, group: 'Правовой режим земли и застройки', ru: 'Лесной статус участка', gr: 'Δασικός χάρτης, πράξη χαρακτηρισμού', issuer: 'Δασαρχείο', blocking: 'yes', cond: null, period: null },
      { id: '1.13', stage: 1, group: 'Правовой режим земли и застройки', ru: 'Береговая линия и зона пляжа', gr: 'Οριοθέτηση αιγιαλού και παραλίας', issuer: 'Κτηματική Υπηρεσία', blocking: 'cond', cond: 'да, для прибрежных', period: null },
      { id: '1.14', stage: 1, group: 'Правовой режим земли и застройки', ru: 'Археологические ограничения', gr: 'Έγκριση Εφορείας Αρχαιοτήτων', issuer: 'Εφορεία Αρχαιοτήτων', blocking: 'yes', cond: null, period: null },
      { id: '1.15', stage: 1, group: 'Правовой режим земли и застройки', ru: 'Природоохранные ограничения (Natura, зоны)', gr: 'Natura 2000, περιβαλλοντικοί όροι', issuer: 'Περιφέρεια', blocking: 'cond', cond: 'по объекту', period: null },
      { id: '1.16', stage: 1, group: 'Правовой режим земли и застройки', ru: 'Доступ к участку: дорога, сервитут, юридический проезд', gr: 'Πρόσβαση, δουλεία διόδου', issuer: 'ΥΔΟΜ / кадастр', blocking: 'yes', cond: null, period: null },
      { id: '1.17', stage: 1, group: 'Правовой режим земли и застройки', ru: 'Наличие подключений: электричество, вода, канализация', gr: 'ΔΕΔΔΗΕ, ΔΕΥΑ', issuer: 'Коммунальные операторы', blocking: 'yes', cond: null, period: null },
      { id: '1.18', stage: 1, group: 'Существующие строения (если объект с постройкой)', ru: 'Разрешение на строительство + утвержденные чертежи', gr: 'Οικοδομική άδεια και εγκεκριμένα σχέδια', issuer: 'ΥΔΟΜ / архив', blocking: 'yes', cond: null, period: null },
      { id: '1.19', stage: 1, group: 'Существующие строения (если объект с постройкой)', ru: 'Справка инженера об отсутствии самостроя', gr: 'Βεβαίωση μηχανικού περί μη αυθαιρέτων (Ν.4495/2017)', issuer: 'Наш инженер', blocking: 'yes', cond: null, period: null },
      { id: '1.20', stage: 1, group: 'Существующие строения (если объект с постройкой)', ru: 'Легализация самостроя, если есть', gr: 'Δήλωση υπαγωγής αυθαιρέτου, βεβαίωση περαίωσης', issuer: 'Инженер', blocking: 'cond', cond: 'да, если есть', period: null },
      { id: '1.21', stage: 1, group: 'Существующие строения (если объект с постройкой)', ru: 'Электронное удостоверение здания', gr: 'Ηλεκτρονική Ταυτότητα Κτιρίου', issuer: 'Инженер', blocking: 'yes', cond: null, period: null },
      { id: '1.22', stage: 1, group: 'Существующие строения (если объект с постройкой)', ru: 'Энергетический сертификат', gr: 'Πιστοποιητικό Ενεργειακής Απόδοσης (ΠΕΑ)', issuer: 'Энергоаудитор', blocking: 'yes', cond: null, period: null },
      { id: '1.23', stage: 1, group: 'Существующие строения (если объект с постройкой)', ru: 'Технический отчет о состоянии конструкций', gr: 'Τεχνική έκθεση', issuer: 'Наш инженер', blocking: 'yes', cond: null, period: null },
      { id: '1.24', stage: 1, group: 'Существующие строения (если объект с постройкой)', ru: 'Отчет о статике / несущей способности', gr: 'Στατική μελέτη / έλεγχος', issuer: 'Инженер-конструктор', blocking: 'cond', cond: 'по объекту', period: null },
      { id: '1.25', stage: 1, group: 'Налоги и платежи продавца', ru: 'Справка об уплате налога на недвижимость за 5 лет', gr: 'Πιστοποιητικό ΕΝΦΙΑ', issuer: 'ΑΑΔΕ', blocking: 'yes', cond: null, period: null },
      { id: '1.26', stage: 1, group: 'Налоги и платежи продавца', ru: 'Декларация Е9 продавца по объекту', gr: 'Δήλωση Ε9', issuer: 'ΑΑΔΕ', blocking: 'yes', cond: null, period: null },
      { id: '1.27', stage: 1, group: 'Налоги и платежи продавца', ru: 'Справка муниципалитета об уплате ТАП', gr: 'Βεβαίωση ΤΑΠ', issuer: 'Δήμος', blocking: 'yes', cond: null, period: null },
      { id: '1.28', stage: 1, group: 'Налоги и платежи продавца', ru: 'Налоговая и страховая чистота продавца', gr: 'Φορολογική και ασφαλιστική ενημερότητα', issuer: 'ΑΑΔΕ / ΕΦΚΑ', blocking: 'yes', cond: null, period: null },
      { id: '1.29', stage: 1, group: 'Налоги и платежи продавца', ru: 'Отсутствие долгов за коммунальные услуги', gr: '-', issuer: 'Операторы', blocking: 'yes', cond: null, period: null },
      { id: '1.30', stage: 1, group: 'Наша сторона (готовность покупателя)', ru: 'Греческий налоговый номер AFM на покупателя', gr: null, issuer: 'Адвокат / ΔΟΥ', blocking: 'yes', cond: null, period: null },
      { id: '1.31', stage: 1, group: 'Наша сторона (готовность покупателя)', ru: 'Греческий банковский счет', gr: null, issuer: 'Банк', blocking: 'yes', cond: null, period: null },
      { id: '1.32', stage: 1, group: 'Наша сторона (готовность покупателя)', ru: 'Доверенность на адвоката с апостилем и переводом', gr: null, issuer: 'Нотариус', blocking: 'yes', cond: null, period: null },
      { id: '1.33', stage: 1, group: 'Наша сторона (готовность покупателя)', ru: 'Подтверждение происхождения средств (AML)', gr: null, issuer: 'Наш финотдел', blocking: 'yes', cond: null, period: null },
      { id: '1.34', stage: 1, group: 'Наша сторона (готовность покупателя)', ru: 'Документ о ввозе средств в Грецию (для будущей репатриации)', gr: null, issuer: 'Банк', blocking: 'yes', cond: null, period: null },
      { id: '1.35', stage: 1, group: 'Наша сторона (готовность покупателя)', ru: 'Решение о структуре владения: физлицо, греческая компания, польский холдинг', gr: null, issuer: 'ПЛ + налоговый консультант', blocking: 'yes', cond: null, period: null },
      { id: '2.1', stage: 2, group: null, ru: 'Предварительный договор с условиями и сроками', gr: 'Προσύμφωνο / ιδιωτικό συμφωνητικό', issuer: null, blocking: 'yes', cond: null, period: null },
      { id: '2.2', stage: 2, group: null, ru: 'Документ о задатке с прописанным механизмом возврата', gr: 'Απόδειξη προκαταβολής', issuer: null, blocking: 'yes', cond: null, period: null },
      { id: '2.3', stage: 2, group: null, ru: 'Оценка объекта для налоговой', gr: 'Αντικειμενική αξία, φύλλο υπολογισμού', issuer: null, blocking: 'yes', cond: null, period: null },
      { id: '2.4', stage: 2, group: null, ru: 'Декларация и оплата налога на переход права', gr: 'Δήλωση φόρου μεταβίβασης (3%)', issuer: null, blocking: 'yes', cond: null, period: null },
      { id: '2.5', stage: 2, group: null, ru: 'Основной нотариальный договор', gr: 'Συμβόλαιο αγοραπωλησίας', issuer: null, blocking: 'yes', cond: null, period: null },
      { id: '2.6', stage: 2, group: null, ru: 'Регистрация в кадастре / ипотечном бюро', gr: 'Μεταγραφή στο Κτηματολόγιο', issuer: null, blocking: 'yes', cond: null, period: null },
      { id: '2.7', stage: 2, group: null, ru: 'Справка о регистрации на нового собственника', gr: 'Πιστοποιητικό μεταγραφής', issuer: null, blocking: 'yes', cond: null, period: null },
      { id: '2.8', stage: 2, group: null, ru: 'Платежные документы: все переводы только банком, наличные исключены', gr: '-', issuer: null, blocking: 'yes', cond: null, period: null },
      { id: '2.9', stage: 2, group: null, ru: 'Акт приема-передачи объекта с фотофиксацией', gr: 'Πρωτόκολλο παράδοσης-παραλαβής', issuer: null, blocking: 'yes', cond: null, period: null },
      { id: '2.10', stage: 2, group: null, ru: 'Передача ключей под подпись, смена замков', gr: '-', issuer: null, blocking: 'yes', cond: null, period: null },
      { id: '2.11', stage: 2, group: null, ru: 'Внесение объекта в Е9 нового собственника', gr: 'Δήλωση Ε9', issuer: null, blocking: 'yes', cond: null, period: null },
      { id: '2.12', stage: 2, group: null, ru: 'Переоформление коммунальных договоров на нас', gr: 'ΔΕΔΔΗΕ, ΔΕΥΑ', issuer: null, blocking: 'yes', cond: null, period: null },
      { id: '3.1', stage: 3, group: null, ru: 'Задание на проектирование от заказчика', gr: '-', issuer: 'Наша команда', blocking: 'yes', cond: null, period: null },
      { id: '3.2', stage: 3, group: null, ru: 'Договор с архитектором и инженерами (фикс цена, сроки, авторские права наши)', gr: 'Ιδιωτικό συμφωνητικό', issuer: 'ПЛ / юрист', blocking: 'yes', cond: null, period: null },
      { id: '3.3', stage: 3, group: null, ru: 'Эскизный проект и планировки', gr: 'Προμελέτη', issuer: 'Архитектор', blocking: 'yes', cond: null, period: null },
      { id: '3.4', stage: 3, group: null, ru: 'Согласование эскиза с заказчиком (подписанное)', gr: '-', issuer: 'ПЛ', blocking: 'yes', cond: null, period: null },
      { id: '3.5', stage: 3, group: null, ru: 'Архитектурный проект', gr: 'Αρχιτεκτονική μελέτη', issuer: 'Архитектор', blocking: 'yes', cond: null, period: null },
      { id: '3.6', stage: 3, group: null, ru: 'Конструктив', gr: 'Στατική μελέτη', issuer: 'Инженер-конструктор', blocking: 'yes', cond: null, period: null },
      { id: '3.7', stage: 3, group: null, ru: 'Инженерные сети: электрика, вода, канализация, отопление', gr: 'Ηλεκτρομηχανολογικές μελέτες (Η/Μ)', issuer: 'Инженер', blocking: 'yes', cond: null, period: null },
      { id: '3.8', stage: 3, group: null, ru: 'Энергетическое исследование', gr: 'Μελέτη ενεργειακής απόδοσης (ΚΕΝΑΚ)', issuer: 'Инженер', blocking: 'yes', cond: null, period: null },
      { id: '3.9', stage: 3, group: null, ru: 'Проект пожарной безопасности', gr: 'Μελέτη πυροπροστασίας', issuer: 'Инженер', blocking: 'cond', cond: 'по объекту', period: null },
      { id: '3.10', stage: 3, group: null, ru: 'Согласование археологии на проект', gr: 'Έγκριση Αρχαιολογίας', issuer: 'Εφορεία Αρχαιοτήτων', blocking: 'yes', cond: null, period: null },
      { id: '3.11', stage: 3, group: null, ru: 'Согласование архитектурного совета (для зон с регламентом)', gr: 'Έγκριση ΣΥΠΟΘΑ / Αρχιτεκτονικής Επιτροπής', issuer: 'Комиссия', blocking: 'cond', cond: 'по зоне', period: null },
      { id: '3.12', stage: 3, group: null, ru: 'Разрешение на застройку', gr: 'Έγκριση δόμησης', issuer: 'ΥΔΟΜ', blocking: 'yes', cond: null, period: null },
      { id: '3.13', stage: 3, group: null, ru: 'Разрешение на строительство', gr: 'Άδεια δόμησης', issuer: 'ΥΔΟΜ', blocking: 'yes', cond: null, period: null },
      { id: '3.14', stage: 3, group: null, ru: 'План безопасности и охраны труда', gr: 'ΣΑΥ - ΦΑΥ', issuer: 'Инженер', blocking: 'yes', cond: null, period: null },
      { id: '3.15', stage: 3, group: null, ru: 'Регистрация стройки в фонде соцстрахования', gr: 'ΑΜΟΕ / ΕΦΚΑ οικοδομοτεχνικό έργο', issuer: 'Бухгалтерия', blocking: 'yes', cond: null, period: null },
      { id: '3.16', stage: 3, group: null, ru: 'Смета по проекту (детальная, по разделам)', gr: 'Προϋπολογισμός έργου', issuer: 'Наша команда', blocking: 'yes', cond: null, period: null },
      { id: '3.17', stage: 3, group: null, ru: 'График реализации с вехами', gr: 'Χρονοδιάγραμμα', issuer: 'Наша команда', blocking: 'yes', cond: null, period: null },
      { id: '3.18', stage: 3, group: null, ru: 'Разрешение на изменение назначения (для Таверны)', gr: 'Άδεια αλλαγής χρήσης', issuer: 'ΥΔΟΜ', blocking: 'cond', cond: 'да, для конверсии', period: null },
      { id: '4.1', stage: 4, group: null, ru: 'Тендерный лист: минимум 3 предложения по каждому крупному пакету работ', gr: null, issuer: null, blocking: 'yes', cond: null, period: null },
      { id: '4.2', stage: 4, group: null, ru: 'Проверка подрядчика: регистрация, AFM, налоговая чистота, страховки, портфолио', gr: null, issuer: null, blocking: 'yes', cond: null, period: null },
      { id: '4.3', stage: 4, group: null, ru: 'Договор подряда: объем, цена, сроки, штрафы за просрочку, гарантия', gr: null, issuer: null, blocking: 'yes', cond: null, period: null },
      { id: '4.4', stage: 4, group: null, ru: 'Приложение: техзадание и спецификация материалов с брендами', gr: null, issuer: null, blocking: 'yes', cond: null, period: null },
      { id: '4.5', stage: 4, group: null, ru: 'Приложение: график платежей строго по факту выполненных этапов', gr: null, issuer: null, blocking: 'yes', cond: null, period: null },
      { id: '4.6', stage: 4, group: null, ru: 'Приложение: форма акта выполненных работ', gr: null, issuer: null, blocking: 'yes', cond: null, period: null },
      { id: '4.7', stage: 4, group: null, ru: 'Удержание гарантийной суммы 5-10% до подписания финального акта', gr: null, issuer: null, blocking: 'yes', cond: null, period: null },
      { id: '4.8', stage: 4, group: null, ru: 'Страхование строительно-монтажных рисков', gr: null, issuer: null, blocking: 'yes', cond: null, period: null },
      { id: '4.9', stage: 4, group: null, ru: 'Страхование ответственности подрядчика', gr: null, issuer: null, blocking: 'yes', cond: null, period: null },
      { id: '4.10', stage: 4, group: null, ru: 'Доверенности: кто и что имеет право подписывать на месте, с лимитами сумм', gr: null, issuer: null, blocking: 'yes', cond: null, period: null },
      { id: '4.11', stage: 4, group: null, ru: 'Реестр всех договоров по объекту с датами и суммами', gr: null, issuer: null, blocking: 'yes', cond: null, period: null },
      { id: '5.1', stage: 5, group: null, ru: 'Журнал работ', gr: null, issuer: null, blocking: 'no', cond: null, period: 'ежедневно / еженедельно' },
      { id: '5.2', stage: 5, group: null, ru: 'Фотоотчет с фиксированных точек съемки', gr: null, issuer: null, blocking: 'no', cond: null, period: 'еженедельно' },
      { id: '5.3', stage: 5, group: null, ru: 'Отчет технадзора', gr: null, issuer: null, blocking: 'no', cond: null, period: 'ежемесячно' },
      { id: '5.4', stage: 5, group: null, ru: 'Акты скрытых работ (арматура, гидроизоляция, подземные сети)', gr: null, issuer: null, blocking: 'no', cond: null, period: 'по факту' },
      { id: '5.5', stage: 5, group: null, ru: 'Протоколы испытаний бетона', gr: null, issuer: null, blocking: 'no', cond: null, period: 'каждая заливка' },
      { id: '5.6', stage: 5, group: null, ru: 'Сертификаты и накладные на материалы', gr: null, issuer: null, blocking: 'no', cond: null, period: 'по поставке' },
      { id: '5.7', stage: 5, group: null, ru: 'Акты выполненных работ с процентом готовности', gr: null, issuer: null, blocking: 'no', cond: null, period: 'ежемесячно' },
      { id: '5.8', stage: 5, group: null, ru: 'Реестр платежей подрядчикам: счет, акт, платежка', gr: null, issuer: null, blocking: 'no', cond: null, period: 'ежемесячно' },
      { id: '5.9', stage: 5, group: null, ru: 'Отчет об отклонениях от бюджета и графика', gr: null, issuer: null, blocking: 'no', cond: null, period: 'ежемесячно' },
      { id: '5.10', stage: 5, group: null, ru: 'Реестр изменений проекта с подписью заказчика', gr: null, issuer: null, blocking: 'no', cond: null, period: 'по факту' },
      { id: '5.11', stage: 5, group: null, ru: 'Протоколы совещаний по объекту с решениями и сроками', gr: null, issuer: null, blocking: 'no', cond: null, period: 'еженедельно' },
      { id: '5.12', stage: 5, group: null, ru: 'Обновление инспекций разрешения (промежуточные проверки ΥΔΟΜ)', gr: null, issuer: null, blocking: 'no', cond: null, period: 'по этапам' },
      { id: '6.1', stage: 6, group: null, ru: 'Финальный акт приема работ с перечнем недоделок', gr: 'Πρωτόκολλο παραλαβής', issuer: null, blocking: 'yes', cond: null, period: null },
      { id: '6.2', stage: 6, group: null, ru: 'Исполнительная документация as-built', gr: 'Σχέδια ως κατασκευάσθη', issuer: null, blocking: 'yes', cond: null, period: null },
      { id: '6.3', stage: 6, group: null, ru: 'Отметка о завершении строительства в разрешении', gr: 'Θεώρηση περαίωσης άδειας', issuer: null, blocking: 'yes', cond: null, period: null },
      { id: '6.4', stage: 6, group: null, ru: 'Обновленное электронное удостоверение здания', gr: 'Ηλεκτρονική Ταυτότητα Κτιρίου (ενημέρωση)', issuer: null, blocking: 'yes', cond: null, period: null },
      { id: '6.5', stage: 6, group: null, ru: 'Новый энергосертификат по факту', gr: 'ΠΕΑ', issuer: null, blocking: 'yes', cond: null, period: null },
      { id: '6.6', stage: 6, group: null, ru: 'Подключение электричества постоянное', gr: 'Ηλεκτροδότηση ΔΕΔΔΗΕ', issuer: null, blocking: 'yes', cond: null, period: null },
      { id: '6.7', stage: 6, group: null, ru: 'Подключение воды и канализации / септик', gr: 'ΔΕΥΑ, βόθρος / βιολογικός', issuer: null, blocking: 'yes', cond: null, period: null },
      { id: '6.8', stage: 6, group: null, ru: 'Акт о вводе объекта в реестр Е9 с новой площадью', gr: 'Δήλωση Ε9', issuer: null, blocking: 'yes', cond: null, period: null },
      { id: '6.9', stage: 6, group: null, ru: 'Гарантийные документы на оборудование и работы', gr: 'Εγγυήσεις', issuer: null, blocking: 'yes', cond: null, period: null },
      { id: '6.10', stage: 6, group: null, ru: 'Инструкция по эксплуатации и обслуживанию объекта', gr: '-', issuer: null, blocking: 'no', cond: null, period: null },
      { id: '6.11', stage: 6, group: null, ru: 'Финальная себестоимость объекта: свод всех затрат', gr: '-', issuer: null, blocking: 'yes', cond: null, period: null },
      { id: '6.12', stage: 6, group: null, ru: 'Для конверсии Таверны: подтверждение завершенной смены назначения', gr: 'Βεβαίωση ολοκλήρωσης αλλαγής χρήσης', issuer: null, blocking: 'yes', cond: null, period: null },
      { id: '6.13', stage: 6, group: null, ru: 'Для отеля: лицензия на эксплуатацию и регистрация', gr: 'Ειδικό Σήμα Λειτουργίας, ΜΗΤΕ / АМА', issuer: null, blocking: 'cond', cond: 'да, для отеля', period: null },
      { id: '7.1', stage: 7, group: null, ru: 'Бизнес-план объекта (по единому оглавлению)', gr: null, issuer: 'Проектная команда', blocking: 'no', cond: null, period: null },
      { id: '7.2', stage: 7, group: null, ru: 'Финансовая модель: вход, capex, продажа, доходность, сценарии', gr: null, issuer: 'Проектная команда', blocking: 'no', cond: null, period: null },
      { id: '7.3', stage: 7, group: null, ru: 'Прайс-лист по лотам с шагом цены и условиями', gr: null, issuer: 'ПЛ утверждает', blocking: 'no', cond: null, period: null },
      { id: '7.4', stage: 7, group: null, ru: 'Планировки с площадями по каждому лоту', gr: null, issuer: 'Архитектор', blocking: 'no', cond: null, period: null },
      { id: '7.5', stage: 7, group: null, ru: '3D визуализации экстерьера и интерьера', gr: null, issuer: 'Маркетинг', blocking: 'no', cond: null, period: null },
      { id: '7.6', stage: 7, group: null, ru: 'Видео с дрона и облет территории', gr: null, issuer: 'Маркетинг', blocking: 'no', cond: null, period: null },
      { id: '7.7', stage: 7, group: null, ru: 'Фото готовых элементов и стройплощадки', gr: null, issuer: 'Маркетинг', blocking: 'no', cond: null, period: null },
      { id: '7.8', stage: 7, group: null, ru: 'Спецификация отделки: что входит в цену, что нет', gr: null, issuer: 'Проектная команда', blocking: 'no', cond: null, period: null },
      { id: '7.9', stage: 7, group: null, ru: 'Брошюра PDF: польский, английский, украинский', gr: null, issuer: 'Маркетинг', blocking: 'no', cond: null, period: null },
      { id: '7.10', stage: 7, group: null, ru: 'Карточка объекта на сайте с полями из общей схемы', gr: null, issuer: 'Маркетинг', blocking: 'no', cond: null, period: null },
      { id: '7.11', stage: 7, group: null, ru: 'Локационный пакет: расстояния до моря, аэропорта, школ, инфраструктуры', gr: null, issuer: 'Маркетинг', blocking: 'no', cond: null, period: null },
      { id: '7.12', stage: 7, group: null, ru: 'Аргументы УТП: обособленность, энергонезависимость, безопасность, укрытие', gr: null, issuer: 'Маркетинг', blocking: 'no', cond: null, period: null },
      { id: '7.13', stage: 7, group: null, ru: 'Расчет доходности от аренды с обоснованием ставок', gr: null, issuer: 'Проектная команда', blocking: 'no', cond: null, period: null },
      { id: '7.14', stage: 7, group: null, ru: 'Пакетные предложения (авто в комплекте и подобное) с расчетом', gr: null, issuer: 'ПЛ', blocking: 'no', cond: null, period: null },
      { id: '7.15', stage: 7, group: null, ru: 'График строительства для покупателя, публичная версия', gr: null, issuer: 'Проектная команда', blocking: 'no', cond: null, period: null },
      { id: '7.16', stage: 7, group: null, ru: 'FAQ по объекту для отдела продаж', gr: null, issuer: 'Маркетинг', blocking: 'no', cond: null, period: null },
      { id: '8.1', stage: 8, group: null, ru: 'Титул на нашу компанию, зарегистрированный', gr: 'Τίτλος, μεταγραφή', issuer: null, blocking: 'no', cond: null, period: null },
      { id: '8.2', stage: 8, group: null, ru: 'Свежая справка об обременениях (не старше 30 дней на момент сделки)', gr: 'Πιστοποιητικό βαρών', issuer: null, blocking: 'no', cond: null, period: null },
      { id: '8.3', stage: 8, group: null, ru: 'Актуальная топосъемка', gr: 'Τοπογραφικό διάγραμμα', issuer: null, blocking: 'no', cond: null, period: null },
      { id: '8.4', stage: 8, group: null, ru: 'Справка об отсутствии самостроя', gr: 'Βεβαίωση μηχανικού', issuer: null, blocking: 'no', cond: null, period: null },
      { id: '8.5', stage: 8, group: null, ru: 'Электронное удостоверение здания', gr: 'Ηλεκτρονική Ταυτότητα Κτιρίου', issuer: null, blocking: 'no', cond: null, period: null },
      { id: '8.6', stage: 8, group: null, ru: 'Энергосертификат', gr: 'ΠΕΑ', issuer: null, blocking: 'no', cond: null, period: null },
      { id: '8.7', stage: 8, group: null, ru: 'Справка ЕНФИА за 5 лет на нашу компанию', gr: 'Πιστοποιητικό ΕΝΦΙΑ', issuer: null, blocking: 'no', cond: null, period: null },
      { id: '8.8', stage: 8, group: null, ru: 'Справка ТАП муниципалитета', gr: 'Βεβαίωση ΤΑΠ', issuer: null, blocking: 'no', cond: null, period: null },
      { id: '8.9', stage: 8, group: null, ru: 'Налоговая и страховая чистота нашей компании', gr: 'Ενημερότητες', issuer: null, blocking: 'no', cond: null, period: null },
      { id: '8.10', stage: 8, group: null, ru: 'Разрешение на строительство и акт завершения', gr: 'Άδεια δόμησης, περαίωση', issuer: null, blocking: 'no', cond: null, period: null },
      { id: '8.11', stage: 8, group: null, ru: 'Правила совместного владения (для комплексов)', gr: 'Κανονισμός πολυκατοικίας, σύσταση οριζοντίου ιδιοκτησίας', issuer: null, blocking: 'no', cond: null, period: null },
      { id: '8.12', stage: 8, group: null, ru: 'Раздел на горизонтальные и вертикальные доли (для нескольких вилл на участке)', gr: 'Σύσταση οριζοντίου / καθέτου ιδιοκτησίας', issuer: null, blocking: 'no', cond: null, period: null },
      { id: '9.1', stage: 9, group: null, ru: 'Форма брони с суммой резервации и сроком', gr: null, issuer: null, blocking: 'no', cond: null, period: null },
      { id: '9.2', stage: 9, group: null, ru: 'Проверка покупателя: KYC, происхождение средств', gr: null, issuer: null, blocking: 'no', cond: null, period: null },
      { id: '9.3', stage: 9, group: null, ru: 'Предварительный договор с графиком платежей', gr: null, issuer: null, blocking: 'no', cond: null, period: null },
      { id: '9.4', stage: 9, group: null, ru: 'Договор рассрочки, если применяется: первый взнос, срок, ставка', gr: null, issuer: null, blocking: 'no', cond: null, period: null },
      { id: '9.5', stage: 9, group: null, ru: 'Механизм обеспечения по рассрочке: сохранение права собственности до полной оплаты или ипотека в нашу пользу', gr: null, issuer: null, blocking: 'no', cond: null, period: null },
      { id: '9.6', stage: 9, group: null, ru: 'Спецификация отделки как приложение к договору', gr: null, issuer: null, blocking: 'no', cond: null, period: null },
      { id: '9.7', stage: 9, group: null, ru: 'Срок передачи и штрафы за просрочку с обеих сторон', gr: null, issuer: null, blocking: 'no', cond: null, period: null },
      { id: '9.8', stage: 9, group: null, ru: 'Нотариальный договор купли-продажи', gr: null, issuer: null, blocking: 'no', cond: null, period: null },
      { id: '9.9', stage: 9, group: null, ru: 'Регистрация в кадастре на покупателя', gr: null, issuer: null, blocking: 'no', cond: null, period: null },
      { id: '9.10', stage: 9, group: null, ru: 'Акт передачи с фотофиксацией и передачей ключей', gr: null, issuer: null, blocking: 'no', cond: null, period: null },
      { id: '9.11', stage: 9, group: null, ru: 'Гарантийный лист покупателю', gr: null, issuer: null, blocking: 'no', cond: null, period: null },
      { id: '9.12', stage: 9, group: null, ru: 'Пакет для покупателя: все техдокументы, гарантии, инструкции', gr: null, issuer: null, blocking: 'no', cond: null, period: null },
      { id: '9.13', stage: 9, group: null, ru: 'Оформление коммунальных договоров на покупателя', gr: null, issuer: null, blocking: 'no', cond: null, period: null },
      { id: '10.1', stage: 10, group: null, ru: 'Юридическое заключение о соответствии объекта порогу и категории', gr: null, issuer: null, blocking: 'no', cond: null, period: null },
      { id: '10.2', stage: 10, group: null, ru: 'Подтверждение завершенной смены назначения до даты подачи', gr: null, issuer: null, blocking: 'no', cond: null, period: null },
      { id: '10.3', stage: 10, group: null, ru: 'Нотариальный договор с указанием суммы не ниже порога', gr: null, issuer: null, blocking: 'no', cond: null, period: null },
      { id: '10.4', stage: 10, group: null, ru: 'Подтверждение оплаты банковским переводом со счета инвестора', gr: null, issuer: null, blocking: 'no', cond: null, period: null },
      { id: '10.5', stage: 10, group: null, ru: 'Регистрация титула', gr: null, issuer: null, blocking: 'no', cond: null, period: null },
      { id: '10.6', stage: 10, group: null, ru: 'Комплект на заявителя: паспорта, справки о несудимости с апостилем, медстраховка, фото, биометрия', gr: null, issuer: null, blocking: 'no', cond: null, period: null },
      { id: '10.7', stage: 10, group: null, ru: 'Документы на членов семьи: свидетельства о браке и рождении с апостилем и переводом', gr: null, issuer: null, blocking: 'no', cond: null, period: null },
      { id: '10.8', stage: 10, group: null, ru: 'Доверенность на адвоката по миграционному делу', gr: null, issuer: null, blocking: 'no', cond: null, period: null },
      { id: '10.9', stage: 10, group: null, ru: 'Расписка о подаче (blue receipt) и трекинг статуса', gr: null, issuer: null, blocking: 'no', cond: null, period: null },
      { id: '10.10', stage: 10, group: null, ru: 'Памятка инвестору: запрет краткосрочной аренды, условия продления, сроки', gr: null, issuer: null, blocking: 'no', cond: null, period: null },
      { id: '11.1', stage: 11, group: null, ru: 'Регистрационный номер объекта краткосрочной аренды (при легальной сдаче, вне Golden Visa)', gr: null, issuer: null, blocking: 'no', cond: null, period: null },
      { id: '11.2', stage: 11, group: null, ru: 'Договор управления объектом', gr: null, issuer: null, blocking: 'no', cond: null, period: null },
      { id: '11.3', stage: 11, group: null, ru: 'Договор аренды, шаблон', gr: null, issuer: null, blocking: 'no', cond: null, period: null },
      { id: '11.4', stage: 11, group: null, ru: 'Страховка объекта', gr: null, issuer: null, blocking: 'no', cond: null, period: null },
      { id: '11.5', stage: 11, group: null, ru: 'График технического обслуживания', gr: null, issuer: null, blocking: 'no', cond: null, period: null },
      { id: '11.6', stage: 11, group: null, ru: 'Ежемесячный отчет по загрузке и доходу', gr: null, issuer: null, blocking: 'no', cond: null, period: null },
      { id: '11.7', stage: 11, group: null, ru: 'Налоговая отчетность по доходу от аренды', gr: null, issuer: null, blocking: 'no', cond: null, period: null },
      { id: 'S.1', stage: 'S', group: null, ru: 'Паспорт объекта: сводная карточка со всеми ключевыми полями', gr: null, issuer: null, blocking: 'no', cond: null, period: 'обновляется' },
      { id: 'S.2', stage: 'S', group: null, ru: 'Реестр документов объекта со статусами и датами истечения', gr: null, issuer: null, blocking: 'no', cond: null, period: 'еженедельно' },
      { id: 'S.3', stage: 'S', group: null, ru: 'Реестр всех платежей по объекту: дата, сумма, получатель, основание, подтверждение', gr: null, issuer: null, blocking: 'no', cond: null, period: 'по факту' },
      { id: 'S.4', stage: 'S', group: null, ru: 'Бухгалтерский учет объекта у нас, не у партнера', gr: null, issuer: null, blocking: 'no', cond: null, period: 'ежемесячно' },
      { id: 'S.5', stage: 'S', group: null, ru: 'Реестр контактов: адвокат, нотариус, инженер, подрядчик, с ролями и лимитами полномочий', gr: null, issuer: null, blocking: 'no', cond: null, period: 'обновляется' },
      { id: 'S.6', stage: 'S', group: null, ru: 'Реестр рисков по объекту со степенью и планом реакции', gr: null, issuer: null, blocking: 'no', cond: null, period: 'ежемесячно' },
      { id: 'S.7', stage: 'S', group: null, ru: 'Архив: скан каждого документа в облаке, доступ у нас, оригиналы в одном сейфе с описью', gr: null, issuer: null, blocking: 'no', cond: null, period: 'по факту' },
      { id: 'S.8', stage: 'S', group: null, ru: 'Протоколы всех встреч с партнерами с фиксацией договоренностей', gr: null, issuer: null, blocking: 'no', cond: null, period: 'по факту' },
      { id: 'S.9', stage: 'S', group: null, ru: 'Отчет по отклонениям бюджета объекта', gr: null, issuer: null, blocking: 'no', cond: null, period: 'ежемесячно' },
    ]
  };
})();
